
stages:
  - prepare-auth
  - build-docker
  - test

update_token:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: prepare-auth
  before_script:
    - aws --version
  script:
    - echo hello
